name: RentalRooms
author: JCThePants
main: com.jcwhatever.rentalrooms.RentalRooms
version: 0.0-beta
depend: [NucleusFramework]
commands:
    rentalrooms:
        aliases: [rent, rental]
        description: Base command for Rental Rooms
        usage: |
            ERROR!