name: RentalRooms
author: JC The Pants
main: com.jcwhatever.bukkit.rental.RentalRooms
version: 0.0-beta
depend: [GenericsLib]
commands:
    rent:
        description: Base command for Rental Rooms
        usage: |
            ERROR!
    rental:
        description: Base command for Rental Rooms
        usage: |
            ERROR!
